#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

echo "Starting infrastructure (MySQL, Mongo, Redis, Kafka, Elasticsearch, Kong)..."
docker compose up -d

echo ""
echo "Infrastructure is up. Apply DB schemas and seed data:"
echo "  ./scripts/init-schemas.sh     # create/upgrade all tables"
echo "  ./scripts/seed-users.sh"
echo "  ./scripts/seed-catalog.sh"
echo "  ./scripts/mark-deals.sh"
echo ""
echo "Service URLs:"
echo "  Kong API Gateway:  http://localhost:8000"
echo "  Kong Admin:        http://localhost:8001"
echo "  Kafka:             localhost:9092"
echo "  Redis:             localhost:6379"
echo "  Elasticsearch:     http://localhost:9200"
echo "  MySQL (user):      localhost:3307"
echo ""
echo "Microservice ports (start from IDE or Maven):"
echo "  user-service          http://localhost:8081"
echo "  catalog-service       http://localhost:8082"
echo "  cart-service          http://localhost:8083"
echo "  order-service         http://localhost:8084"
echo "  payment-service       http://localhost:8085"
echo "  notification-service  http://localhost:8086"
echo "  admin-service         http://localhost:8087/admin/login"
echo ""
echo "Start all services (example):"
echo "  mvn -pl user-service spring-boot:run"
echo "  mvn -pl catalog-service spring-boot:run"
echo "  mvn -pl cart-service spring-boot:run"
echo "  mvn -pl order-service spring-boot:run"
echo "  mvn -pl payment-service spring-boot:run"
echo "  mvn -pl notification-service spring-boot:run"
echo "  mvn -pl admin-service spring-boot:run"
echo ""
echo "Storefront & admin:"
echo "  cd frontend && npm run dev    # http://localhost:5173"
echo "  Admin console                 # http://localhost:8087/admin"
echo ""
echo "Verify everything:"
echo "  ./scripts/check-services.sh"
